#!/bin/bash

# -----------------------------------------------------------
#  06-import-dashboard.sh
#  Imports the Kibana Dashboard from 'export.ndjson'.
# -----------------------------------------------------------

set -e

# 1. Source the Environment Variables (Absolute Path)
#    We look for the file generated by 01-setup-elk.sh in the runtime directory.
ENV_FILE="$HOME/cicd_stack/elk/filebeat/filebeat.env"

if [ -f "$ENV_FILE" ]; then
    source "$ENV_FILE"
else
    echo "❌ Error: Could not find credentials at $ENV_FILE"
    echo "   Did you run 01-setup-elk.sh?"
    exit 1
fi

# 2. Configuration
KIBANA_URL="https://kibana.cicd.local:5601"
DASHBOARD_FILE="export.ndjson"

# 3. Check for the Export File
if [ ! -f "$DASHBOARD_FILE" ]; then
    echo "❌ Error: '$DASHBOARD_FILE' not found in current directory."
    exit 1
fi

echo "⏳ Waiting for Kibana to be ready..."
until curl -s "$KIBANA_URL/api/status" | grep -q "available"; do
  echo -n "."
  sleep 5
done
echo " Kibana is up!"

echo "🚀 Importing Dashboard from $DASHBOARD_FILE..."
echo "---------------------------------------------"

# 4. Import the Dashboard
#    -X POST: The API method
#    -u: Basic Auth using the password from the env file
#    -H "kbn-xsrf: true": Required header for Kibana API
#    --form file=@...: Uploads the file

curl -X POST "$KIBANA_URL/api/saved_objects/_import?overwrite=true" \
  -u "elastic:$ELASTIC_PASSWORD" \
  -H "kbn-xsrf: true" \
  --form file=@$DASHBOARD_FILE

echo ""
echo "---------------------------------------------"
echo "✅ Import request finished."